version: '3.7'

services:
  app:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/shop
      - SPRING_REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop

